version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: typeorm-in-the-nest
    restart: always
    env_file:
      - ./.env
    ports:
      - 5433:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
